- hosts: all
  become: true

  vars:
    nodejs_version: "12.x"
    pip_executable: pip3
    pip_install_packages:
      - name: docker
      - name: docker-compose

  pre_tasks:
    - name: Install FirewallD
      package:
        name: firewalld
        state: present
      when: ansible_os_family == "RedHat"

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
